CREATE TABLE IF NOT EXISTS posts (
	id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
	board VARCHAR(32) NOT NULL,
	title VARCHAR(256) NOT NULL,
	content VARCHAR(10000),
	pinned BOOLEAN NOT NULL DEFAULT 0,
	moderator BOOLEAN NOT NULL DEFAULT FALSE,
	locked BOOLEAN NOT NULL DEFAULT false,
	parent BIGINT UNSIGNED,
	image BIGINT UNSIGNED,
	FOREIGN KEY (board) REFERENCES boards(id),
	FOREIGN KEY (image) REFERENCES images(id),
	FOREIGN KEY (parent) REFERENCES posts(id)
);
