CREATE TABLE IF NOT EXISTS images (
	id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    file_id BIGINT UNSIGNED NOT NULL,
	name VARCHAR(64) NOT NULL,
	content_type VARCHAR(64) NOT NULL,
	hash VARCHAR(64) NOT NULL
);
